version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0-beta1-arm64
    container_name: elastic
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0-alpha2-arm64
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: http://elastic:9200
    networks:
      - elastic
    ports:
      - 5601:5601
    depends_on:
      - elastic


volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge